config/routes.rb
Rails.application.routes.draw do

  get '/top' => 'homes#top'
  root to: 'homes#top'
  get '/about' => 'homes#about'

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }



  # 管理者側のルーティング設定
  namespace :admin do
    # 注文履歴一覧
    root to: 'homes#top'
    # patch 'orders/:id' => 'order_details#update'
    resources :homes, only: [:top]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end



# public
    scope module: :public do
      # post '/customers' => 'customers#create'

      get '/items' => 'items#index'
      get '/items/:id' => 'items#show', as: 'item'


      resource :customers, only:[:edit, :update] do
        collection do
          get 'mypage' => 'customers#show', as: 'mypage'
          get :confirm
          patch 'withdraw' => 'customers#withdraw', as: 'withdraw'
        end
      end
      # get '/customers/mypage' => 'customers#show'
      # get '/customers/mypage/edit' => 'customers#edit', as: 'customer'
      # patch '/customers/mypage' => 'customers#update'
      # get '/customers/confirm' => 'customers#confirm', as: 'confirm'
      # patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

      get '/cart_items' => 'cart_items#index', as: 'cart_items'
      post '/cart_items' => 'cart_items#create'
      patch '/cart_items/:id' => 'cart_items#update', as: 'cart_item'
      delete '/cart_items/:id' => 'cart_items#destroy'
      delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all'

      get '/orders/new' => 'orders#new'
      post '/orders/confirm' => 'orders#confirm', as: 'orders/confirm'
      get '/orders/complete' => 'orders#complete', as: 'complete'
      post '/orders' => 'orders#create'
      get '/orders' => 'orders#index'
      get '/orders/:id' => 'orders#show', as: 'order'





    end



  # 会員側のルーティング設定

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }










  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord


  has_one_attached :image


  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  # belongs_to :genres


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @new = Item.new
    @items = Item.page(params[:page])

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end


  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :is_active)
  end



  def image_params
    params.require(:image).permit(:name, :introduction, :price)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <h2>商品編集</h2>
</div>

<div class="container">
  <div class="row row no-gutters justify-content-center">
    <div class="col-12">
      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

      <div class="row row no-gutters form-group">
        <div class="col-2"></div>
        <%= f.label :商品画像, class: "col-2" %>
        <%= f.file_field :image, accept: "image/*", class: "col-4" %>
      </div>

      <div class="row row no-gutters form-group">
        <div class="col-2"></div>
        <%= f.label :商品名, class: "col-2" %>
        <%= f.text_field :name, class: "col-4" %>
      </div>

      <div class="row row no-gutters form-group">
        <div class="col-2"></div>
        <%= f.label :商品説明, class: "col-2" %>
        <%= f.text_area :introduction, class: "col-4" %>
      </div>

      <div class="row row no-gutters form-group">
        <div class="col-2"></div>
        <%= f.label :税抜価格, class: "col-2" %>
        <%= f.text_field :price, class: "col-4" %> 円
      </div>

      <div class="row row no-gutters form-group">
        <div class="col-2"></div>
        <%= f.label :販売ステータス, class: "col-2" %>
      　<div class="col-4">
        　<%= f.radio_button "is_active", "true", id: "radio1" %>
      　   　<label for="radio1">販売中</label>
        　<%= f.radio_button "is_active", "false", id: "radio2" %>
        　　<label for="radio2">販売停止中</label>
        </div>
      </div>


      <div class="container">
        <div class="text-center">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      </div>
　    <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row row no-gutters justify-content-between align-items-center">
    <div class="col-auto mr-auto">
      <h4>商品一覧</h4>
    </div>
    <div class="col-auto">
      <h1><%= link_to "➕" , new_admin_item_path(@new) %></h1>
    </div>
  </div>
</div>


  <div class="container">
    <div class="row row no-gutters justify-content-center">
      <div class="col-8">
      <table class="table">
        <thead>
          <tr>
      　     <th class="col-1">商品ID</th>
          　<th class="col-3">商品名</th>
          　<th class="col-2">税抜価格</th>
          　<th class="col-2">ステータス</th>
        　</tr>
      　</thead>

      　<tbody>
        　<% @items.each do |item| %>
        　<tr>
          　<td>
          　   <div class="item_id"> <%= item.id %> </div>
            </td>
          　<td>
          　   <div class="item_name">
        　       <%= link_to item.name, admin_item_path(item.id) %>
          　   </div>
  　         </td>
  　         <td>
  　           <div class="item_price">
  　             <%= (item.price).to_s(:delimited) %>
  　           </div>
  　         </td>
  　         <td>
  　           <% if item.is_active %>
    　           <p class="font-weight-bold text-success">販売中</p>
    　         <% else %>
    　          <p>販売停止中</p>
    　        <% end %>
  　         </td>
  　       <% end %>
  　     </tbody>
  　   </table>
  　   <div class="d-flex justify-content-center">
  　     <%= paginate @items %>
  　   </div>
    </div>
  </div>
  </div>

app/views/admin/items/new.html.erb
<div class="container">
  <h4>商品新規登録</h4>
</div>


<div class="container">
  <div class="row row no-gutters justify-content-center">
    <div class="col-12">
      <%= form_with model:@item, url:admin_items_path, local:true do |f| %>

      <div class="row row no-gutters form-group">
        <div class="col-2"></div>
        <%= f.label :商品画像, class: "col-2" %>
        <%= f.file_field :image, accept: "image/*", class: "col-4" %>
      </div>

      <div class="row row no-gutters form-group">
        <div class="col-2"></div>
        <%= f.label :商品名, class: "col-2" %>
        <%= f.text_field :name, class: "col-4" %>
      </div>

      <div class="row row no-gutters form-group">
        <div class="col-2"></div>
        <%= f.label :商品説明, class: "col-2" %>
        <%= f.text_area :introduction, class: "col-4" %>
      </div>

      <div class="row row no-gutters form-group">
        <div class="col-2"></div>
        <%= f.label :税抜価格, class: "col-2" %>
        <%= f.text_field :price, class: "col-4" %> 円
      </div>

      <div class="row row no-gutters form-group">
        <div class="col-2"></div>
        <%= f.label :販売ステータス, class: "col-2" %>
      　<div class="col-4">
        　<%= f.radio_button "is_active", "true", id: "radio1" %>
      　   　<label for="radio1">販売中</label>
        　<%= f.radio_button "is_active", "false", id: "radio2" %>
        　　<label for="radio2">販売停止中</label>
        </div>
      </div>

      <div class="container">
        <div class="text-center">
          <%= f.submit "新規登録", class: "btn btn-success" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h4>商品詳細</h4>
</div>

<div class="container">
  <div class="row row no-gutters">
    <div class="col-2"></div>
      <div class="col-4">
        <div class="image">
          <% if @item.image.attached? %>
            <%= image_tag @item.image, class: "item-image" %>
          <% else %>
            <%= image_tag 'noimage', class: "item-image" %>
          <% end %>
        </div>
      </div>
      <div class="col-6">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td class="col-2">商品名</td>
              <td class="col-4"><%= @item.name %></td>
            </tr>
            <tr>
              <td class="col-2">商品説明</td>
              <td class="col-4"><%= @item.introduction %></td>
            </tr>
            <tr>
              <td class="col-2">税込価格<br>(税抜価格)</td>
             <td class="col-4"><%= (@item.with_tax_price).to_s(:delimited) %>（<%= (@item.price).to_s(:delimited) %>）円</td>
            </tr>
            <tr>
              <td class="col-2">
                <div class="item_status">販売ステータス</div>
    　    　　　　</td>
    　　　   　　<td class="col-4">
    　           <% if @item.is_active %>
      　           <p class="font-weight-bold text-success">販売中</p>
      　         <% else %>
      　          <p>販売停止中</p>
      　        <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
  </div>
</div>
<div class="container">
  <div class="text-center">
    <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
  </div>
</div>
<br><br>