config/routes.rb
Rails.application.routes.draw do

  get '/top' => 'homes#top'
  root to: 'homes#top'
  get '/about' => 'homes#about'

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }



  # 管理者側のルーティング設定
  namespace :admin do
    # 注文履歴一覧
    root to: 'homes#top'
    # patch 'orders/:id' => 'order_details#update'
    resources :homes, only: [:top]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end



# public
    scope module: :public do
      # post '/customers' => 'customers#create'

      get '/items' => 'items#index'
      get '/items/:id' => 'items#show', as: 'item'


      resource :customers, only:[:edit, :update] do
        collection do
          get 'mypage' => 'customers#show', as: 'mypage'
          get :confirm
          patch 'withdraw' => 'customers#withdraw', as: 'withdraw'
        end
      end
      # get '/customers/mypage' => 'customers#show'
      # get '/customers/mypage/edit' => 'customers#edit', as: 'customer'
      # patch '/customers/mypage' => 'customers#update'
      # get '/customers/confirm' => 'customers#confirm', as: 'confirm'
      # patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

      get '/cart_items' => 'cart_items#index', as: 'cart_items'
      post '/cart_items' => 'cart_items#create'
      patch '/cart_items/:id' => 'cart_items#update', as: 'cart_item'
      delete '/cart_items/:id' => 'cart_items#destroy'
      delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all'

      get '/orders/new' => 'orders#new'
      post '/orders/confirm' => 'orders#confirm', as: 'orders/confirm'
      get '/orders/complete' => 'orders#complete', as: 'complete'
      post '/orders' => 'orders#create'
      get '/orders' => 'orders#index'
      get '/orders/:id' => 'orders#show', as: 'order'





    end



  # 会員側のルーティング設定

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }










  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer

  has_many :order_details, dependent: :destroy

	has_many :items, through: :order_details
# 	accepts_nested_attributes_for :ordered_items





  def subtotal
    item.with_tax_price * amount
  end

  enum payment_method: {
    credit_card: 0,
    transfer: 1
  }

  enum order_status: {
    payment_waiting: 0,
    payment_confirmation: 1,
    in_production: 2,
    preparing_delivery: 3,
    delivered: 4
  }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_details
  end

  def update
  	@order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details

    if @order.order_status == "payment_confirmation"
      @order_details.update_all(production_status: 1)
    end

    flash[:success] = "更新に成功しました"
  	redirect_to admin_order_path
  end



private

  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :postage, :amount_billed, :purchase_price, :customer_id, :order_status)
  end

  def order_detail_params
    params.require(:order_detail).permit(:item_id, :purchase_price, :amount, :order_id, :production_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<!--formwithを使って、updateアクション2種類を使い分ける
最後にredirecttoでshowページに戻る-->


<div class="container">
  <h4>注文履歴詳細</h4>
  <div class="row">
    <div class="col-8">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th class="col-2">購入者</th>
            <td class="col-4"><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
          </tr>
          <tr>
            <th class="col-2">注文日</th>
            <td class="col-4"><%= @order.created_at.strftime("%Y/%-m/%-d") %></td>
          </tr>
          <tr>
            <th class="col-2">配送先</th>
            <td class="col-4">
              〒<%= @order.postal_code %><br>
              <%= @order.address %><br>
              <%= @order.name %>
            </td>
          </tr>
          <tr>
            <th class="col-2">支払方法</th>
            <td class="col-4"><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <th class="col-2">注文ステータス</th>
            <td class="col-4">
              <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
                <!--< %= f.select :order_status, Order.order_statuses.keys, class: "order_status" %>-->
                <%= f.select :order_status, Order.order_statuses_i18n.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"),k]}, class: "order_status" %>
                <!--enumのフォーム モデル名.statuses_i18n.keys.map {|k| [I18n.t("enumの記述.#{k}"),k]}-->
                <%= f.submit "更新" , class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="col-2">商品名</th>
            <th class="col-2">単価（税込）</th>
            <th class="col-1">数量</th>
            <th class="col-1">小計</th>
            <th class="col-2">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <!--< % subtotal = 0 %>-->
          <% @order_items.each do |order_item| %>
          <tr>
            <td class="col-2"><%= order_item.item.name %></td>
            <td class="col-2"><%= (order_item.purchase_price).to_s(:delimited) %></td>
            <td class="col-1"><%= order_item.amount %></td>
            <td class="col-1"><%= (order_item.subtotal).to_s(:delimited) %></td>
            <td class="col-2">
              <%= form_with model: order_item, url: admin_order_detail_path(order_item) , method: :patch , local: true do |f| %>
                <!--< %= f.select :order_details, OrderDetail.production_statuses %>-->
                <%= f.select :production_status, OrderDetail.production_statuses_i18n.keys.map {|k| [I18n.t("enums.order_detail.production_status.#{k}"),k]} %>
                <!--enum日本語化フォーム→モデル名.statuses_i18n.keys.map {|k| [I18n.t("enumの記述.#{k}"),k]}-->
                <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-4">
      <table class="table table-borderless">
        <br>
        <br>
        <tbody>
          <tr>
            <% sum = 0 %>
            <% @order_items.each do |order_item| %>
            <% sum += order_item.subtotal %>
            <% end %>
            <th class="col-2">商品合計</th>
            <td class="col-2"><%= (sum.to_i).to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th class="col-2">送料</th>
            <td class="col-2">
              <% @order.postage = 800 %>
              <%= (@order.postage).to_s(:delimited) %>円
            </td>
          </tr>
          <tr>
            <th class="col-2">請求合計額</th>
            <td class="col-2">
              <% @order.amount_billed = @order.postage + sum.to_i %>
                <%= @order.amount_billed.to_s(:delimited) %>円
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>