config/routes.rb
Rails.application.routes.draw do

  get '/top' => 'homes#top'
  root to: 'homes#top'
  get '/about' => 'homes#about'

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }



  # 管理者側のルーティング設定
  namespace :admin do
    # 注文履歴一覧
    root to: 'homes#top'
    # patch 'orders/:id' => 'order_details#update'
    resources :homes, only: [:top]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end



# public
    scope module: :public do
      # post '/customers' => 'customers#create'

      get '/items' => 'items#index'
      get '/items/:id' => 'items#show', as: 'item'


      resource :customers, only:[:edit, :update] do
        collection do
          get 'mypage' => 'customers#show', as: 'mypage'
          get :confirm
          patch 'withdraw' => 'customers#withdraw', as: 'withdraw'
        end
      end
      # get '/customers/mypage' => 'customers#show'
      # get '/customers/mypage/edit' => 'customers#edit', as: 'customer'
      # patch '/customers/mypage' => 'customers#update'
      # get '/customers/confirm' => 'customers#confirm', as: 'confirm'
      # patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

      get '/cart_items' => 'cart_items#index', as: 'cart_items'
      post '/cart_items' => 'cart_items#create'
      patch '/cart_items/:id' => 'cart_items#update', as: 'cart_item'
      delete '/cart_items/:id' => 'cart_items#destroy'
      delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all'

      get '/orders/new' => 'orders#new'
      post '/orders/confirm' => 'orders#confirm', as: 'orders/confirm'
      get '/orders/complete' => 'orders#complete', as: 'complete'
      post '/orders' => 'orders#create'
      get '/orders' => 'orders#index'
      get '/orders/:id' => 'orders#show', as: 'order'





    end



  # 会員側のルーティング設定

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }










  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    # @orders = customer.orders.includes(:order_details)
    @orders = Order.page(params[:page])
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :postage,
    :amount_billed, :purchase_price, :customer_id)
  end

  def order_detail_params
  params.permit(:item_id, :purchase_price, :amount, :order_id)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @items = Item.order('id DESC').limit(4)
    # ASCだと古い順でDESCで新着順です。

  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :price)
  end



  def image_params
    params.require(:image).permit(:name, :introduction, :price)
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container">
  <div class="row row no-gutters justify-content-center">
    <div class="about">About</div>
  </div>
</div>

<div class="container">
  <div class="row row no-gutters justify-content-center">
      <h5 class="text-center">
        ながのCAKEは全国発送可能なケーキ屋さんです。<br>
        お子様からお年寄りの方までお召し上がりいただけるよう、<br>
        様々なバリエーションをご用意しております。<br>
        また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
        ぜひご注文ください。<br>
      </h5>
    </div>
  </div>
</div>


<div class="container">
  <div class="row row no-gutters justify-content-center">
    <%= image_tag 'タルト.jpeg', class: "item-image3" %>
  </div>
</div>

app/views/homes/top.html.erb
<br />
<div class="container">
  <div class="row justify-content-center">
    <div class="text-left">
    ようこそ、ながのCAKEへ！<br>
    このサイトは、ケーキ販売のECサイトになります。<br>
    会員でない方も商品の閲覧はできますが、<br>
    購入には会員登録が必要になります。<br>
    </div>
  </div>
</div>



<div class="container">
  <h3 class="bold">新着商品</h3>
    <div class="row row no-gutters">
      <% @items.each do |item| %>
      <div class="col-3 px-2 my-2">
        <div class="image">
        <!--each分は単数形のみには使用しない-->
          <% if item.image.attached? %>
            <%= image_tag item.image, size: "400x300", class: "item-image" %>
          <% else %>
            <%= image_tag 'noimage', size: "400x300", class: "item-image" %>
          <% end %>
        </div>
        <div class="bold"><%= link_to item.name, item_path(item.id) %></div>
        <%= number_to_currency(item.with_tax_price, unit: "￥", strip_insignificant_zeros: true) %>
      </div>
      <% end %>
    </div>
    <p class="text-right">
      <%= link_to "全ての商品を見る > ", items_path(current_customer) %>
　　</p>
</div>