config/routes.rb
Rails.application.routes.draw do

  get '/top' => 'homes#top'
  root to: 'homes#top'
  get '/about' => 'homes#about'

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }



  # 管理者側のルーティング設定
  namespace :admin do
    # 注文履歴一覧
    root to: 'homes#top'
    # patch 'orders/:id' => 'order_details#update'
    resources :homes, only: [:top]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end



# public
    scope module: :public do
      # post '/customers' => 'customers#create'

      get '/items' => 'items#index'
      get '/items/:id' => 'items#show', as: 'item'


      resource :customers, only:[:edit, :update] do
        collection do
          get 'mypage' => 'customers#show', as: 'mypage'
          get :confirm
          patch 'withdraw' => 'customers#withdraw', as: 'withdraw'
        end
      end
      # get '/customers/mypage' => 'customers#show'
      # get '/customers/mypage/edit' => 'customers#edit', as: 'customer'
      # patch '/customers/mypage' => 'customers#update'
      # get '/customers/confirm' => 'customers#confirm', as: 'confirm'
      # patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

      get '/cart_items' => 'cart_items#index', as: 'cart_items'
      post '/cart_items' => 'cart_items#create'
      patch '/cart_items/:id' => 'cart_items#update', as: 'cart_item'
      delete '/cart_items/:id' => 'cart_items#destroy'
      delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all'

      get '/orders/new' => 'orders#new'
      post '/orders/confirm' => 'orders#confirm', as: 'orders/confirm'
      get '/orders/complete' => 'orders#complete', as: 'complete'
      post '/orders' => 'orders#create'
      get '/orders' => 'orders#index'
      get '/orders/:id' => 'orders#show', as: 'order'





    end



  # 会員側のルーティング設定

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }










  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :customer
  belongs_to :item

  validates :item_id, :amount, presence: true
  validates :amount, numericality:{ only_integer: true }

  def subtotal
    item.with_tax_price * amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy


  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord


  has_one_attached :image


  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  # belongs_to :genres


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer

  has_many :order_details, dependent: :destroy

	has_many :items, through: :order_details
# 	accepts_nested_attributes_for :ordered_items





  def subtotal
    item.with_tax_price * amount
  end

  enum payment_method: {
    credit_card: 0,
    transfer: 1
  }

  enum order_status: {
    payment_waiting: 0,
    payment_confirmation: 1,
    in_production: 2,
    preparing_delivery: 3,
    delivered: 4
  }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  def subtotal
    item.with_tax_price * amount
  end


  def with_tax_price
    (price * 1.1).floor
  end

  enum production_status: {
    production_not_possible: 0,
    production_pending: 1,
    in_production: 2,
    production_complete: 3
  }


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    # @orders = customer.orders.includes(:order_details)
    @orders = Order.page(params[:page])
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :postage,
    :amount_billed, :purchase_price, :customer_id)
  end

  def order_detail_params
  params.permit(:item_id, :purchase_price, :amount, :order_id)
  end


end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



  before_action :configure_sign_up_params, if: :devise_controller?


  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end




  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when Customer
      root_path
    end
  end

  # def after_sign_up_path_for(resource)
    # case resource
    # when Admin
      # admin_path
    # when Customer
      # public_end_users_show_path
    # end
  # end

  # def after_sign_out_path_for(resource)
    # if resource == :admin
      # new_admin_session_path
    # else
    # root_path
    # end
  # end

  # protect_from_forgery with: :exception

  helper_method :current_cart_items

  # def current_cart_items
  #   current_customer
  #     # ユーザーとカートの紐付け
  #     current_cart_items = current_customer || current_customer.create_cart_items!

  # end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @items = Item.order('id DESC').limit(4)
    # ASCだと古い順でDESCで新着順です。

  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :price)
  end



  def image_params
    params.require(:image).permit(:name, :introduction, :price)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <div class="header">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <span><a class="navbar-brand" href="/"><%= image_tag 'logo_n04.png',size: "200x100" %></a></span>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">

              <% if current_customer %>
                <%= link_to "マイページ", mypage_customers_path, class: "btn btn-outline-secondary" %>
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
                <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary" %>
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary" %>
              <% elsif current_admin %>
                <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary" %>
                <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary" %>
                <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-secondary" %>
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" %>
              <% else %>
                <%= link_to "About", about_path, class: "btn btn-outline-secondary" %>
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
                <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary" %>
                <%= link_to "ログイン", customer_session_path, class: "btn btn-outline-secondary" %>
              <% end %>
            </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <%= yield %>
    <div class="footer">
      <div class="container">
        <p class="text-center">CopyRight Infratop.inc</p><br>
      </div>
    </div>

  </body>

</html>